blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://github.com/jmuelbert/anniversaryreminder/wiki/FAQ
    about: You may find your question and the answer to it here.
  - name: Documentation
    url: http://jmuelbert.github.io/anniversaryreminder/
    about: The documentation tells you how to use anniversaryreminder.
