---
# SPDX-FileCopyrightText: © 2016-2023 Jürgen Mülbert
#
# SPDX-License-Identifier: EUPL-1.2
#

name: size-limit

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: 🧰 Checkout Source Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1


      - uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d # v1.8.0 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
