---
name: Vale checks
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
        - name: 🧰 Checkout Source Code
          uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

        - name: Check markdown files for Vale errors
          uses: errata-ai/vale-action@reviewdog
          with:
            # github-pr-check, github-pr-review, github-check
            reporter: github-pr-check
